### Solutions - Module 6 ###


3. Create 3 new functions named as below. Each function must print messages as specified.
  + genericErrorHandler => "Generic Error handled"
  + typeErrorHandler => "Type Error handled"
  + referenceErrorHandler => "Reference Error handled"
    Change the first function, to throw one error type at a time and handle this errors with the functions created in the previous task.
    Note: make sure that the first error thrown does not prevent the others to be thrown.

##### exercise 1 #####
```javascript
function throwError(){
  throw new Error();
}

throwError();
```

##### exercise 2 #####
```javascript
function throwError(){
  throw new Error();
}

try{
  throwError();
} catch (e) {
  console.log('this error was throw:', e);
}
```

##### exercise 3 #####
```javascript

var errorTypeEnum = {
  TypeError: 1,
  ReferenceError: 2,
  CustomError: 3
};


 function throwError(type){
   switch (type) {
     case errorTypeEnum.TypeError:
       throw new TypeError();
       break;
     case errorTypeEnum.ReferenceError:
       throw new ReferenceError();
       break;
     case errorTypeEnum.CustomError:
       throw 'myCustomError';
       break;
     default:
       throw new Error();
   }
 }
 
 function genericErrorHandler(e){
   console.log('Generic error handled', e);
 }
 
 function typeErrorHandler(e){
   console.log('Type Error handled', e);
 }
 
 function referenceErrorHandler(e){
   console.log('Reference Error handled', e);
 }

 try {
   throwError(0);
 } catch (e) {
   genericErrorHandler(e);
 } finally {

    try {
      throwError(errorTypeEnum.TypeError);
    } catch(e) {
      typeErrorHandler(e);
    } finally {

        try {
            throwError(errorTypeEnum.ReferenceError);
        } catch (e) {
          referenceErrorHandler(e);
        } finally {

          try {
            throwError(errorTypeEnum.CustomError);
          } catch (e) {
            genericErrorHandler(e);
          }
        }
    }
 }
```
